"""add_vehicle_id_to_rides

Revision ID: 59952a803750
Revises: 9b1baaf4287c
Create Date: 2026-03-22 14:23:34.057207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59952a803750'
down_revision: Union[str, Sequence[str], None] = '9b1baaf4287c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rides', sa.Column('vehicle_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'rides', 'vehicles', ['vehicle_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rides', type_='foreignkey')
    op.drop_column('rides', 'vehicle_id')
    # ### end Alembic commands ###
