"""Add price_per_seat to rides

Revision ID: 6782d29d9789
Revises: 59952a803750
Create Date: 2026-03-23 14:05:32.119861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6782d29d9789'
down_revision: Union[str, Sequence[str], None] = '59952a803750'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add column as nullable first
    op.add_column('rides', sa.Column('price_per_seat', sa.Integer(), nullable=True))
    
    # Set default value for existing rows
    op.execute("UPDATE rides SET price_per_seat = 0")
    
    # Now make it NOT NULL
    op.alter_column('rides', 'price_per_seat', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rides', 'price_per_seat')
    # ### end Alembic commands ###
