"""add_vehicles_table

Revision ID: 9b1baaf4287c
Revises: ab2d2f38a668
Create Date: 2026-03-22 14:07:17.453938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9b1baaf4287c'
down_revision: Union[str, Sequence[str], None] = 'ab2d2f38a668'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('make', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=False),
    sa.Column('license_plate', sa.String(length=20), nullable=False),
    sa.Column('type', sa.Enum('CAR', 'BIKE', name='vehicletype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_plate')
    )
    op.alter_column('booking_history', 'occurred_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('booking_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('booking_history_event_id_key'), 'booking_history', type_='unique')
    op.drop_index(op.f('idx_booking_history_occurred_at'), table_name='booking_history')
    op.drop_index(op.f('idx_booking_history_user_id'), table_name='booking_history')
    op.create_index(op.f('ix_booking_history_booking_id'), 'booking_history', ['booking_id'], unique=False)
    op.create_index(op.f('ix_booking_history_event_id'), 'booking_history', ['event_id'], unique=True)
    op.create_index(op.f('ix_booking_history_occurred_at'), 'booking_history', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_booking_history_ride_id'), 'booking_history', ['ride_id'], unique=False)
    op.create_index(op.f('ix_booking_history_user_id'), 'booking_history', ['user_id'], unique=False)
    op.drop_constraint(op.f('booking_history_ride_id_fkey'), 'booking_history', type_='foreignkey')
    op.drop_constraint(op.f('booking_history_booking_id_fkey'), 'booking_history', type_='foreignkey')
    op.drop_constraint(op.f('booking_history_user_id_fkey'), 'booking_history', type_='foreignkey')
    op.create_foreign_key(None, 'booking_history', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'booking_history', 'rides', ['ride_id'], ['id'])
    op.create_foreign_key(None, 'booking_history', 'bookings', ['booking_id'], ['id'])
    op.alter_column('booking_idempotency', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_foreign_key(None, 'booking_idempotency', 'bookings', ['booking_id'], ['id'])
    op.alter_column('bookings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_bookings_passenger'), table_name='bookings')
    op.drop_index(op.f('idx_bookings_ride'), table_name='bookings')
    op.drop_index(op.f('idx_bookings_status'), table_name='bookings')
    op.drop_index(op.f('unique_active_ride_passenger'), table_name='bookings', postgresql_where="((status)::text = 'CONFIRMED'::text)")
    op.drop_constraint(op.f('bookings_passenger_id_fkey'), 'bookings', type_='foreignkey')
    op.drop_constraint(op.f('bookings_ride_id_fkey'), 'bookings', type_='foreignkey')
    op.create_foreign_key(None, 'bookings', 'rides', ['ride_id'], ['id'])
    op.create_foreign_key(None, 'bookings', 'users', ['passenger_id'], ['id'])
    op.alter_column('notification_attempts', 'processed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('notification_attempts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_notification_attempts_event_id'), table_name='notification_attempts')
    op.create_index(op.f('ix_notification_attempts_event_id'), 'notification_attempts', ['event_id'], unique=False)
    op.alter_column('outbox_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('processed_events', 'processed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('rides', 'departure_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('rides', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_rides_destination_coords'), table_name='rides')
    op.drop_index(op.f('idx_rides_search'), table_name='rides')
    op.drop_index(op.f('idx_rides_source_coords'), table_name='rides')
    op.drop_constraint(op.f('rides_driver_id_fkey'), 'rides', type_='foreignkey')
    op.create_foreign_key(None, 'rides', 'users', ['driver_id'], ['id'])
    op.alter_column('users', 'password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'])
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'password_hash',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'rides', type_='foreignkey')
    op.create_foreign_key(op.f('rides_driver_id_fkey'), 'rides', 'users', ['driver_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_rides_source_coords'), 'rides', ['source_lat', 'source_lng'], unique=False)
    op.create_index(op.f('idx_rides_search'), 'rides', ['source', 'destination', 'departure_time'], unique=False)
    op.create_index(op.f('idx_rides_destination_coords'), 'rides', ['destination_lat', 'destination_lng'], unique=False)
    op.alter_column('rides', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('rides', 'departure_time',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('processed_events', 'processed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('outbox_events', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_notification_attempts_event_id'), table_name='notification_attempts')
    op.create_index(op.f('idx_notification_attempts_event_id'), 'notification_attempts', ['event_id'], unique=False)
    op.alter_column('notification_attempts', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('notification_attempts', 'processed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.create_foreign_key(op.f('bookings_ride_id_fkey'), 'bookings', 'rides', ['ride_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('bookings_passenger_id_fkey'), 'bookings', 'users', ['passenger_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('unique_active_ride_passenger'), 'bookings', ['ride_id', 'passenger_id'], unique=True, postgresql_where="((status)::text = 'CONFIRMED'::text)")
    op.create_index(op.f('idx_bookings_status'), 'bookings', ['status'], unique=False)
    op.create_index(op.f('idx_bookings_ride'), 'bookings', ['ride_id'], unique=False)
    op.create_index(op.f('idx_bookings_passenger'), 'bookings', ['passenger_id'], unique=False)
    op.alter_column('bookings', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'booking_idempotency', type_='foreignkey')
    op.alter_column('booking_idempotency', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'booking_history', type_='foreignkey')
    op.drop_constraint(None, 'booking_history', type_='foreignkey')
    op.drop_constraint(None, 'booking_history', type_='foreignkey')
    op.create_foreign_key(op.f('booking_history_user_id_fkey'), 'booking_history', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('booking_history_booking_id_fkey'), 'booking_history', 'bookings', ['booking_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('booking_history_ride_id_fkey'), 'booking_history', 'rides', ['ride_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_booking_history_user_id'), table_name='booking_history')
    op.drop_index(op.f('ix_booking_history_ride_id'), table_name='booking_history')
    op.drop_index(op.f('ix_booking_history_occurred_at'), table_name='booking_history')
    op.drop_index(op.f('ix_booking_history_event_id'), table_name='booking_history')
    op.drop_index(op.f('ix_booking_history_booking_id'), table_name='booking_history')
    op.create_index(op.f('idx_booking_history_user_id'), 'booking_history', ['user_id'], unique=False)
    op.create_index(op.f('idx_booking_history_occurred_at'), 'booking_history', ['occurred_at'], unique=False)
    op.create_unique_constraint(op.f('booking_history_event_id_key'), 'booking_history', ['event_id'])
    op.alter_column('booking_history', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('booking_history', 'occurred_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_table('vehicles')
    # ### end Alembic commands ###
